language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: amsterdamphoto.org
env:
- REMOTE_DIR_STAGE=web/staging.amsterdamphoto.org/public_html REMOTE_DIR_PROD=web/amsterdamphoto.org/public_html
  REMOTE_HOST=amsterdamphoto.org
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0b6c03e7cb09_key -iv $encrypted_0b6c03e7cb09_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -azP $TRAVIS_BUILD_DIR/out/ $SSH_STAGE_USER@$REMOTE_HOST:$REMOTE_DIR_STAGE
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: rsync -azP $TRAVIS_BUILD_DIR/out/ $SSH_PROD_USER@$REMOTE_HOST:$REMOTE_DIR_PROD
  on:
    branch: master
